In [4]:
import numpy as np
A = np.array([[0,1], [2,3], [4,5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
B = np.array([[0,1,2,3], [4,5,6,7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
AB = np.dot(A, B)
AB

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [21]:
print(AB.max())

47
